### PR TITLE
Update cLib to CQC version 2

### PR DESCRIPTION
**Pull request by Wojtek242**
Bring the cLib up to date.

This is not a re-design, but only an update to a new version. However, I did clean up a few things such as the Makefile and the includes.

### CODE REVIEW

**Comment by Wojtek242** [comment]
Addresses issue #61

**Comment by Wojtek242** [comment]
Wait, I just noticed I committed binaries. Let me clean this up first. You can still check if it works though.

**Comment by Wojtek242** [comment]
Ok, good to go

**Comment by AckslD** [comment]
@Wojtek242 The C library have now been moved to https://github.com/SoftwareQuTech/CQC-C so with the files in this current branch. So I'm closing this pull request.

**Pull request closed without merging**
