### PR TITLE
rustLib

### PR DESCRIPTION
**Pull request by Wojtek242**
This pull request provides a sample integration with the Rust CQC library which is available on [crates.io](https://crates.io/crates/cqc).

- [crates.io page](https://crates.io/crates/cqc)
- [GitHub repository](https://github.com/Wojtek242/cqc)
- [Documentation](https://docs.rs/cqc)

The tests provided here are simple and mirror those provided by the C library. The `cqc` crate itself is more comprehensively tested.

Note that this PR includes a Dockerfile in the root of the repository. It is documented within the comments in the file itself. Let me know if you would prefer the Dockerfile to not be committed or committed elsewhere/separately.

### CODE REVIEW

**Comment by AckslD** [comment]
Hi @Wojtek242 !

Sorry for taking so long but I'm finally trying this out. Unfortunetaly I'm getting problems when trying to run the tests for the rust library. I'm getting the following errors:

```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_gates-3ffa566a1dcdc099

running 1 test
Testing |0> preparation......................
test test_gates ... test test_gates has been running for over 60 seconds
thread 'test_gates' panicked at 'Z target precision not met, got -0.02 expected 1.0.
', tests/test_gates.rs:105:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test test_gates ... FAILED

failures:

failures:
    test_gates

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test test_gates'
```

**Comment by Wojtek242** [comment]
Hi @AckslD 

Thanks for finding some time to have a look! The error looks weird. At first I thought that it was due to the test being probabilistic, but getting `-0.02` where you should have `1.0` is quite the error. Also, for testing `|0>`, the error in Z should be 0! 

I can't reproduce your error on my branch sadly as everything works on the version of Simulaqron that I have on my fork. To try and reproduce your error, could you tell me if you ran it in the docker container or did you install the rust toolchain and ran it on your machine? Also, did you merge the updates first and then test so you would be running on an updated version of SimulaQron? A possible source of the issue could be some updates to the SimulaQron.

I tried running it on the newest SimulaQron code base as well, but it's sending packets back I can't make sense of. The header claims it's version 2, but I don't see that anywhere in the code that it has been updated. 

Are the internal events in CQC logged anywhere so I can try and make sense of what is being sent back?

**Comment by Wojtek242** [comment]
@AckslD 

Sounds good. In case you don't find anything, can you please get a packet capture for me since I can't reproduce your problem.

To do that, start the container with an extra parameter
```
docker run -v $(pwd):/workspace/SimulaQron --name rust_lib_test simulaqron
```
within it, go to `cqc/rustLib` as usual, but before you start the test open a new terminal window.

From the new terminal window attach to the container with
```
docker exec -it rust_lib_test bash
```
Run the following commands
```
apt install -y tcpdump
tcpdump -i lo -w rust_lib_test.pcap
```
Now go back to the original terminal and run the test as usual
```
./tests/run_test.sh
```
When the test fails, go to the terminal in which you are running tcpdump and stop the capture with ctrl+c

You can now close the container and the terminal window. You should now have the file `rust_lib_test.pcap` in the root of your SimulaQron directory - can you please attach the file.

**Comment by Wojtek242** [comment]
> @Wojtek242
> 
> I used the docker container and the version of SimulaQron which is in this branch. I'm not sure why this is happening but will see if I can investigate. But it might not happen until next week.
> 
> I'm confused that you say that you get CQC version 2. Is this in the Develop branch? Looking at the `cqcHeader.py` in Develop it says `CQC_VERSION = 1`.

Yes, I'm confused about the version as well. I'll figure out what's going on when updating.

**Comment by Wojtek242** [comment]
So turns out on the newest version of Develop `startAll.sh` wasn't executing correctly which caused it skip the generation of the config files and thus my test was connecting to the wrong port and receiving data that just happened to have 2 in its first byte and confusing it for the version.

I don't think this has anything to do with the issue you are seeing, but I updated the Dockerfile and the run_test.sh which will make sure it has no issues with the newer version of SimulaQron. It works for me on both the original branch and when merged with an up-to-date Develop branch.

**Comment by AckslD** [comment]
@Wojtek242 
I'm not sure if that's what did the trick but I pulled your latest push and now the tests pass :)

Three comments:

- The third gate-test says that it's testing |1> preparation, however it's actually preparation in the y-basis.
- I would suggest to have the tolerance in the deviation from expectation value depend on the number of iterations. In the tests for PythonLib we put the tolerance to be `conf / sqrt(iterations)`. This makes it easier to only change the number of iterations and one can keep the `conf` variable fixed.
- Would it be possible for you to write some documentation on the rustLib which I can add to the docs?

 I think the Dockerfile is very good btw and can be useful for people to get started. I will add a section in the documentation on how to do this when merging.

**Comment by Wojtek242** [comment]
That's great! I will apply your feedback some time soon.

What format do you want the docs to be in? Should I just write more in the current README.md?

**Comment by Wojtek242** [comment]
@AckslD 

Done. I updated both the docs and the test.

It's worth noting that the documentation I wrote basically sends the reader to https://docs.rs/cqc which will always be more up to date. The rustLib directory is more of a demo than a proper library.

I did additionally spend some extra time updating the docs of the crate itself as well.

**Pull request merged**
