### PR TITLE
Network and cli

### PR DESCRIPTION
**Pull request by AckslD**
Major update:

- All shell scripts to start SimulaQron are now gone. One can either start a network using a commands line interface which was started by @cgmcintyr as `./cli/SimulaQron.py network start-all` or by instantiating an object of the class `simulaqron.network.Network` and calling its method `start`.
- All tests are now unittest and not started through shell scripts.

There is still some cleanup and documentation to be done before I merge, but feel free to try it out before.

### CODE REVIEW

**Comment by Wojtek242** [comment]
Trying to run the `rustLib` tests inside a docker container with 
```
$simulaqron_path/cli/SimulaQron.py network start-all --nrnodes 2 &
```
doesn't work. I just get an `Aborted!` message. Any suggestions where to look for logs?

Besides that I have some usability comments:

- I would be interested in a `quiet` option that suppresses output (possibly different options to suppress only non-error output or to suppress all output)

- I think there's too much redundant hierarchy in the CLI. I have to type out:
```
./cli/SimulaQron.py network start-all
```
before I can even specify `--nrnodes`. Given that there are no other options at the first two levels at all is there any reason for this nesting?

One side effect of this is that all the interesting options are hidden from `--help` until I type those two levels as well. For example to figure out what to run, I tried the following steps
```
./cli/SimulaQron.py --help
./cli/SimulaQron.py network --help
./cli/SimulaQron.py network start-all --help
```
so I ran three help commands before getting to what I wanted.

Unless there are plans to expand the options available at the different levels, I would flatten the hierarchy so that by running `./cli/SimulaQron.py --help` I already get enough guidance to run something interesting.

**Comment by AckslD** [comment]
@Wojtek242 I agree with your comments regarding the hierarchy of the CLI. How about `./cli/SimulaQron.py start` starts the network and `./cli/SimulaQron.py -h` directly gives more info about options such as `--nodes` etc. I also think something like `--quiet` is a good idea. I would also like to add the possibility to set settings here, for example by `./cli/SimulaQron.py set backend stabilizer` etc.

Regarding your problem, I'm not completely sure why this is the case. For me this happens if I start the network, not as a background process, and for example do CTRL-C. This is because click prints `Aborted!` if a `KeyboardInterrupt` or `EOFError` is raised. For some reason I suspect that the `input` statement which the network is waiting at raises an `EOFError` for you when you start it as a background process. I'm not sure why this is the case at this point.

**Comment by Wojtek242** [comment]
Having a `start` and a `set` option on the first level makes sense so the first level of `help` could tell the user that they can either run the simulator or change the settings so I like those ideas. I think with this setup you would only get info about `--nodes` of you run `start --help` which makes sense to me as you don't want to be setting `--nodes` with the `set` option (or do you?).

I'll investigate my error at some point a bit more later.

**Comment by AckslD** [comment]
@Wojtek242 I've pushed changes for having a `start` commands as well as `set` and `get` for settings. Did you manage to figure out something more regarding the bug?

**Comment by Wojtek242** [comment]
I've only found out that the same command works without a problem inside the docker container if run from the shell directly. I have no idea at the moment why there would be a problem running it from a script? I wonder if there is an in-built assumption somewhere that the script has access to stdin...

**Comment by Wojtek242** [comment]
The script no longer aborts if I pipe anything into it. However, I think that kills it as well. Which bit of code can I change so that "press any button to kill the network" is ignored? This would test my hypothesis.

**Comment by Wojtek242** [comment]
The network does not abort if I do not set it to run as a background task in the script, but then this blocks any tests from running.

**Comment by AckslD** [comment]
@Wojtek242 I made some changes which will hopefully make it better now. If you start the network as before as `SimulaQron start` it does not block (I've also remove the .py extension). Then to stop the network you simply do `SimulaQron stop`. You can also have multiple networks running if you give them different names with the `--name` flag. Let me know if it works for you. Note that you don't need to do add the `&` anymore.

**Pull request merged**
