### PR TITLE
136 move files to simulaqron

### PR DESCRIPTION
**Pull request by AckslD**
Breaking change!

This moves the folders `general`, `local`, `toolbox` and `virtNode` and the files `configFiles.py` and `settings.py` to a folder `simulaqron`, such that imports should be done as `simulaqron.xxx`. Accordingly the PYTHONPATH should now be set to `/your/path/SimulaQron`. Imports of cqc should now instead be `from cqc.pythonLib import CQCConnection`.

### CODE REVIEW

**Comment by mdskrzypczyk** [comment]
@AckslD I've found a bug with the pull request, it seems that "simulaqron" is mispelled as "simulqron" in a few places:

`(qutech) blacksheep@ranch:~/Documents/qutech/SimulaQron$ grep -iR "simulqron" .
./tests/runTests.sh:         has_qutip=$(${simulaqron_path}/simulqron/toolbox/has_module.py qutip)
./tests/runTests.sh:         has_projectq=$(${simulaqron_path}/simulqron/toolbox/has_module.py projectq)
./simulaqron/settings.py:        else:  # default simulqron  (elif backend_handler.lower() == "simulqron")`

**Comment by AckslD** [comment]
Thanks @mdskrzypczyk . I fixed this now.

**Comment by Wojtek242** [comment]
I've hit two errors:
- One was an incorrect path to `get_simulaqron_path.py` in `rustLib`'s `run_tests.sh`, it should be `../../../simulaqron/toolbox/get_simulaqron_path.py` (you forgot the `simulaqron` directory)
- Given that projectq and qutip are now optional, what is the supported way of running SimulaQron? Just running `run_tests.sh` complain about `projectq` not being installed. The way it tries to start the nodes is with `$simulaqron_path/run/startAll.sh --nrnodes 2 &`

**Comment by AckslD** [comment]
@Wojtek242 Thanks! I fixed the issues. The default backend is now the stabilizer backend which requires neither qutip nor projectq.

**Comment by Wojtek242** [comment]
Cool, `rustLib` works now.

You can also simplify the `Dockerfile` a bit. I had to add some ugly hacks to make all the pip installs work with `qutip` and `projectq`, but now that they're gone from `requirements.txt` they're no longer a problem.

You can replace
```
# SimulaQron dependencies
# projectq fails to install without pybind11 pre-installed
# qutip is also badly behaved so installed separately
RUN pip install pybind11
RUN cat ./requirements.txt | sed /qutip/d | xargs pip install
RUN pip install qutip
```

With
```
# SimulaQron dependencies
RUN pip install -r ./requirements.txt
```

**Comment by AckslD** [comment]
@Wojtek242 Cool, done!

**Pull request merged**
